[package]
name = "odp-core"
description = "Transport-independent protocol primitives for the Offering Discovery Protocol."
documentation = "https://docs.rs/odp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
include_dir.workspace = true
jsonschema.workspace = true
language-tags.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
